"""modified hub model added add address

Revision ID: 2c9b81e2988b
Revises: 1a84048885f0
Create Date: 2025-03-26 17:35:54.821671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c9b81e2988b'
down_revision: Union[str, None] = '1a84048885f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('region', sa.String(length=100), nullable=False))
    op.add_column('hubs', sa.Column('province', sa.String(length=100), nullable=False))
    op.add_column('hubs', sa.Column('municipality_city', sa.String(length=100), nullable=False))
    op.add_column('hubs', sa.Column('barangay', sa.String(length=100), nullable=True))
    op.add_column('hubs', sa.Column('street', sa.String(length=100), nullable=True))
    op.drop_column('hubs', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('hubs', 'street')
    op.drop_column('hubs', 'barangay')
    op.drop_column('hubs', 'municipality_city')
    op.drop_column('hubs', 'province')
    op.drop_column('hubs', 'region')
    # ### end Alembic commands ###
