"""Fixed id sized in member details  model

Revision ID: 2ed6455211b4
Revises: b4449d76a562
Create Date: 2025-03-11 13:05:25.953857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ed6455211b4'
down_revision: Union[str, None] = 'b4449d76a562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_details', 'id',
               existing_type=mysql.VARCHAR(length=18),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_details', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###
