"""added investor enum in admin accounts

Revision ID: 3719a52ea8a4
Revises: 929166923f53
Create Date: 2025-03-20 16:23:58.516193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3719a52ea8a4'
down_revision: Union[str, None] = '929166923f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_accounts', 'account_type',
               existing_type=mysql.ENUM('SUPERADMIN', 'ADMIN', 'CUSTOMER_SUPPORT'),
               type_=sa.Enum('INVESTOR', 'ADMIN', 'CUSTOMER_SUPPORT'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_accounts', 'account_type',
               existing_type=sa.Enum('INVESTOR', 'ADMIN', 'CUSTOMER_SUPPORT'),
               type_=mysql.ENUM('SUPERADMIN', 'ADMIN', 'CUSTOMER_SUPPORT'),
               existing_nullable=False)
    # ### end Alembic commands ###
