"""added merchant purchase history model

Revision ID: 3acd79c33521
Revises: c350c0280569
Create Date: 2025-03-24 10:22:57.625324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acd79c33521'
down_revision: Union[str, None] = 'c350c0280569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_purchases',
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_merchant_purchases_purchase_id'), 'merchant_purchases', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_purchases_purchase_id'), table_name='merchant_purchases')
    op.drop_table('merchant_purchases')
    # ### end Alembic commands ###
