"""Modified extension_type in wallet_model

Revision ID: 6d242c59f889
Revises: 8d8e4388342a
Create Date: 2025-03-11 12:50:27.582805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d242c59f889'
down_revision: Union[str, None] = '8d8e4388342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('wallet_balance', sa.Float(), nullable=False))
    op.add_column('wallets', sa.Column('reward_points', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'reward_points')
    op.drop_column('wallets', 'wallet_balance')
    # ### end Alembic commands ###
