"""initial migration

Revision ID: 8d8e4388342a
Revises: 
Create Date: 2025-03-11 12:42:40.042044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8e4388342a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('community_name', sa.String(length=155), nullable=False),
    sa.Column('community_leader', sa.String(length=10), nullable=True),
    sa.Column('reward_points', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('community_id'),
    sa.UniqueConstraint('community_name')
    )
    op.create_index(op.f('ix_communities_community_id'), 'communities', ['community_id'], unique=False)
    op.create_table('wallet_extensions',
    sa.Column('wallet_extension_id', sa.String(length=36), nullable=False),
    sa.Column('extension_name', sa.String(length=155), nullable=False),
    sa.Column('extension_type', sa.Enum('monetary'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('wallet_extension_id')
    )
    op.create_index(op.f('ix_wallet_extensions_extension_name'), 'wallet_extensions', ['extension_name'], unique=False)
    op.create_index(op.f('ix_wallet_extensions_wallet_extension_id'), 'wallet_extensions', ['wallet_extension_id'], unique=False)
    op.create_table('wallets',
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('public_address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_index(op.f('ix_wallets_wallet_id'), 'wallets', ['wallet_id'], unique=False)
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('mpin', sa.String(length=4), nullable=True),
    sa.Column('account_type', sa.Enum('MEMBER', 'MERCHANT', 'INVESTOR', 'LEADER', 'HUB', 'ADMIN', 'SUPERADMIN', 'CUSTOMER_SUPPORT'), nullable=False),
    sa.Column('referral_id', sa.String(length=12), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('is_kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('admin_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.Enum('SUPERADMIN', 'ADMIN', 'CUSTOMER_SUPPORT'), nullable=False),
    sa.Column('account_url', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mobile_number'], ['members.mobile_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_url'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hub_name', sa.String(length=155), nullable=False),
    sa.Column('hub_user', sa.String(length=36), nullable=False),
    sa.Column('reward_points', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hub_user'], ['members.mobile_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_user')
    )
    op.create_table('investors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investor', sa.String(length=36), nullable=False),
    sa.Column('reward_points', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['investor'], ['members.mobile_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor')
    )
    op.create_table('member_address',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_details',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=155), nullable=False),
    sa.Column('last_name', sa.String(length=155), nullable=False),
    sa.Column('middle_name', sa.String(length=155), nullable=True),
    sa.Column('suffix_name', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_wallets',
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_id', 'member_id')
    )
    op.create_table('member_wallet_extensions',
    sa.Column('member_wallet_extension_id', sa.String(length=36), nullable=False),
    sa.Column('extension_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=155), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['wallet_extensions.wallet_extension_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['member_wallets.wallet_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_wallet_extension_id')
    )
    op.create_index(op.f('ix_member_wallet_extensions_extension_id'), 'member_wallet_extensions', ['extension_id'], unique=False)
    op.create_index(op.f('ix_member_wallet_extensions_external_id'), 'member_wallet_extensions', ['external_id'], unique=False)
    op.create_index(op.f('ix_member_wallet_extensions_wallet_id'), 'member_wallet_extensions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_wallet_extensions_wallet_id'), table_name='member_wallet_extensions')
    op.drop_index(op.f('ix_member_wallet_extensions_external_id'), table_name='member_wallet_extensions')
    op.drop_index(op.f('ix_member_wallet_extensions_extension_id'), table_name='member_wallet_extensions')
    op.drop_table('member_wallet_extensions')
    op.drop_table('member_wallets')
    op.drop_table('member_details')
    op.drop_table('member_address')
    op.drop_table('investors')
    op.drop_table('hubs')
    op.drop_table('admin_accounts')
    op.drop_table('members')
    op.drop_index(op.f('ix_wallets_wallet_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_wallet_extensions_wallet_extension_id'), table_name='wallet_extensions')
    op.drop_index(op.f('ix_wallet_extensions_extension_name'), table_name='wallet_extensions')
    op.drop_table('wallet_extensions')
    op.drop_index(op.f('ix_communities_community_id'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
