"""added merchant models

Revision ID: 973f7f78d2a2
Revises: d5412148440a
Create Date: 2025-03-12 18:45:42.212862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973f7f78d2a2'
down_revision: Union[str, None] = 'd5412148440a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('business_name', sa.String(length=155), nullable=False),
    sa.Column('business_type', sa.String(length=155), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('merchant_wallet', sa.Float(), server_default='0.00', nullable=False),
    sa.Column('reward_points', sa.Float(), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mobile_number'], ['members.mobile_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_merchant_id'), 'merchants', ['merchant_id'], unique=False)
    op.create_table('merchant_details',
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('municipality_city', sa.String(length=100), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchant_details_merchant_id'), 'merchant_details', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_details_merchant_id'), table_name='merchant_details')
    op.drop_table('merchant_details')
    op.drop_index(op.f('ix_merchants_merchant_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
