"""added qr code in merchant model

Revision ID: a506e2d5bdcd
Revises: 973f7f78d2a2
Create Date: 2025-03-13 09:58:03.989241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a506e2d5bdcd'
down_revision: Union[str, None] = '973f7f78d2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('qr_code_url', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'qr_code_url')
    # ### end Alembic commands ###
