"""Fixed id sized in member address model

Revision ID: b4449d76a562
Revises: 6d242c59f889
Create Date: 2025-03-11 13:04:47.675794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4449d76a562'
down_revision: Union[str, None] = '6d242c59f889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_address', 'id',
               existing_type=mysql.VARCHAR(length=18),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_address', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###
