"""modified  merchant purchase history model

Revision ID: bceb6fca572d
Revises: 3acd79c33521
Create Date: 2025-03-24 10:26:42.357745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bceb6fca572d'
down_revision: Union[str, None] = '3acd79c33521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_purchases', sa.Column('reference_id', sa.String(length=120), nullable=False))
    op.add_column('merchant_purchases', sa.Column('extra_metadata', sa.String(length=255), nullable=True))
    op.add_column('merchant_purchases', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('merchant_purchases', sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded'), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_purchases', 'status')
    op.drop_column('merchant_purchases', 'description')
    op.drop_column('merchant_purchases', 'extra_metadata')
    op.drop_column('merchant_purchases', 'reference_id')
    # ### end Alembic commands ###
