"""added activated_by col in activation history model

Revision ID: c350c0280569
Revises: 18f26a59a056
Create Date: 2025-03-21 09:44:48.730620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c350c0280569'
down_revision: Union[str, None] = '18f26a59a056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_history', sa.Column('activated_by', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activation_history', 'activated_by')
    # ### end Alembic commands ###
