"""added reward points in admin accounts

Revision ID: cef94a890f6d
Revises: 2c9b81e2988b
Create Date: 2025-03-27 12:26:32.231236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef94a890f6d'
down_revision: Union[str, None] = '2c9b81e2988b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_accounts', sa.Column('reward_points', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_accounts', 'reward_points')
    # ### end Alembic commands ###
