"""modified purchase and activation model status

Revision ID: d58e5f27d8c7
Revises: 9f3144a5458c
Create Date: 2025-04-03 15:48:59.405822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd58e5f27d8c7'
down_revision: Union[str, None] = '9f3144a5458c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_purchases', 'status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed', 'refunded'),
               type_=sa.Enum('pending', 'success', 'failed', 'refunded'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_purchases', 'status',
               existing_type=sa.Enum('pending', 'success', 'failed', 'refunded'),
               type_=mysql.ENUM('pending', 'completed', 'failed', 'refunded'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    # ### end Alembic commands ###
