"""added merchant referrals model

Revision ID: ee6df761226c
Revises: a506e2d5bdcd
Create Date: 2025-03-13 12:29:46.846476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee6df761226c'
down_revision: Union[str, None] = 'a506e2d5bdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('referred_by', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['members.referral_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_index(op.f('ix_merchant_referrals_referral_id'), 'merchant_referrals', ['referral_id'], unique=False)
    op.drop_column('merchants', 'qr_code_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('qr_code_url', mysql.VARCHAR(length=3000), nullable=True))
    op.drop_index(op.f('ix_merchant_referrals_referral_id'), table_name='merchant_referrals')
    op.drop_table('merchant_referrals')
    # ### end Alembic commands ###
