"""added reward model

Revision ID: f23d4edda858
Revises: f74d412c0d2f
Create Date: 2025-03-26 11:14:53.534294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23d4edda858'
down_revision: Union[str, None] = 'f74d412c0d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reward_source_type', sa.String(length=120), nullable=False),
    sa.Column('reward_points', sa.Float(), nullable=False),
    sa.Column('reward_from', sa.String(length=36), nullable=False),
    sa.Column('receiver', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_from'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    # ### end Alembic commands ###
