"""fix merchant name in merchant_referrals model

Revision ID: f70b3e71adcd
Revises: 3f3e43cbb031
Create Date: 2025-03-13 12:33:43.197676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70b3e71adcd'
down_revision: Union[str, None] = '3f3e43cbb031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_referrals', sa.Column('referred_merchant', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'merchant_referrals', 'merchants', ['referred_merchant'], ['merchant_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchant_referrals', type_='foreignkey')
    op.drop_column('merchant_referrals', 'referred_merchant')
    # ### end Alembic commands ###
